---

- name: configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Update apt and install docker
  yum:
    name: docker
    state: latest
    update_cache: true

- name: Start docker
  ansible.builtin.systemd:
    name: docker
    state: started